// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 strlen()", "[example]")
{
	int srclen, tgtlen;
	char source[100] = "Chocolate\0";
	char target[100];

	srclen = mycstrlen(source);
	cout << "The length of source string " << srclen << endl;
	REQUIRE(srclen == 9);

	mycstrcpy(source, target);
	tgtlen = mycstrlen(target);
	cout << "The length of target string " << tgtlen << endl;
	cout << "The Target String is " << target << endl;
	cout << "****************************************\n";
	REQUIRE(tgtlen == 9);

	REQUIRE(strcmp(target, "Chocolate") == 0);
}

// tests for exercise 2
TEST_CASE("Ex2 strcat()", "[example]")
{
	int srclen;
	char source[100] = "Chocolate\0";
	char target[100] = "Chips";
	srclen = mycstrcat(source, target);
	cout << "The length of source string " << srclen << endl;
	cout << "The Concatenated String is " << source << endl;
	REQUIRE(srclen == strlen(source));
	REQUIRE(strcmp(source, "ChocolateChips") == 0);
}
